// Single source of truth for the project file format (project.json).
// Every load/save goes through ProjectSchema.parse so bad files fail loudly.
// Older schema versions are migrated on parse (see migrateProject); new fields carry zod defaults so old data fills in.
import { z } from 'zod';

export const SCHEMA_VERSION = 2;

export const EasingSchema = z.discriminatedUnion('type', [
  z.object({ type: z.literal('linear') }),
  z.object({ type: z.literal('easeIn') }),
  z.object({ type: z.literal('easeOut') }),
  z.object({ type: z.literal('easeInOut') }),
  z.object({
    type: z.literal('cubicBezier'),
    x1: z.number().min(0).max(1),
    y1: z.number(),
    x2: z.number().min(0).max(1),
    y2: z.number(),
  }),
  z.object({
    type: z.literal('spring'),
    stiffness: z.number().positive(),
    damping: z.number().nonnegative(),
    mass: z.number().positive(),
  }),
]);
export type Easing = z.infer<typeof EasingSchema>;

/** Animatable values are numbers or CSS hex colours (#rrggbb / #rrggbbaa). */
export const KeyValueSchema = z.union([z.number(), z.string()]);

export const KeyframeSchema = z.object({
  id: z.string(),
  /** Seconds, relative to the layer's start. */
  time: z.number(),
  value: KeyValueSchema,
  /** Easing used from this keyframe to the next one. */
  easing: EasingSchema,
  /** Set when generated by an animation preset, so re-applying can replace it. */
  source: z.string().optional(),
});
export type Keyframe = z.infer<typeof KeyframeSchema>;

export const BLEND_MODES = [
  'normal', 'multiply', 'screen', 'overlay', 'darken', 'lighten', 'color-dodge', 'color-burn',
  'hard-light', 'soft-light', 'difference', 'exclusion', 'hue', 'saturation', 'color', 'luminosity',
] as const;
export const BlendModeSchema = z.enum(BLEND_MODES);
export type BlendMode = z.infer<typeof BlendModeSchema>;

const LayerBase = {
  id: z.string(),
  name: z.string(),
  visible: z.boolean(),
  locked: z.boolean(),
  /** Seconds relative to the scene start. */
  start: z.number().min(0),
  duration: z.number().positive(),
  /** Anchor in normalised layer-local coordinates (0..1). */
  anchorX: z.number(),
  anchorY: z.number(),
  x: z.number(),
  y: z.number(),
  scale: z.number(),
  rotation: z.number(),
  opacity: z.number().min(0).max(1),
  /** Property name -> keyframes (sorted by time). */
  keyframes: z.record(z.string(), z.array(KeyframeSchema)),
  // ---- effects (v2) — sizes in project pixels, scaled with the layer's own scale when drawn
  blur: z.number().min(0).default(0),
  /** Drop shadow on/off (kept separate from the colour so toggling never touches values or keyframes). */
  shadow: z.boolean().default(false),
  shadowColor: z.string().default('#00000040'),
  shadowBlur: z.number().min(0).default(0),
  /** Screen-space offset (not rotated with the layer). */
  shadowOffsetX: z.number().default(0),
  shadowOffsetY: z.number().default(0),
  blendMode: BlendModeSchema.default('normal'),
};

export const FillModeSchema = z.enum(['solid', 'linear']);

export const TextAnimSchema = z.object({
  unit: z.enum(['char', 'word', 'line']),
  effect: z.enum(['fade', 'rise', 'drop', 'scale', 'typewriter', 'blur']),
  order: z.enum(['forward', 'reverse', 'center', 'edges', 'random']),
  /** Seconds between consecutive units. */
  stagger: z.number().min(0),
  /** Seconds each unit takes. */
  duration: z.number().positive(),
  /** In: seconds after the layer starts. Out: seconds before the layer ends. */
  delay: z.number().min(0),
  /** Pixels for rise/drop/blur. */
  distance: z.number(),
  easing: EasingSchema,
  seed: z.number().int(),
  /** Typewriter only: show a blinking caret after the last visible character. */
  caret: z.boolean().default(false),
});
export type TextAnim = z.infer<typeof TextAnimSchema>;

export const TextLayerSchema = z.object({
  ...LayerBase,
  type: z.literal('text'),
  content: z.string(),
  fontFamily: z.string(),
  fontSize: z.number().positive(),
  fontWeight: z.number().int().min(100).max(900),
  lineHeight: z.number().positive(),
  letterSpacing: z.number(),
  align: z.enum(['left', 'center', 'right']),
  color: z.string(),
  fillMode: FillModeSchema.default('solid'),
  gradientTo: z.string().default('#ffffff'),
  /** Degrees. 0 = left→right, 90 = top→bottom. */
  gradientAngle: z.number().default(90),
  stroke: z.string().default('#000000'),
  strokeWidth: z.number().min(0).default(0),
  textIn: TextAnimSchema.nullable().default(null),
  textOut: TextAnimSchema.nullable().default(null),
});

export const ImageLayerSchema = z.object({
  ...LayerBase,
  type: z.literal('image'),
  assetId: z.string(),
  width: z.number().positive(),
  height: z.number().positive(),
});

export const SHAPE_KINDS = ['rect', 'ellipse', 'triangle', 'star', 'polygon', 'line'] as const;
export const ShapeKindSchema = z.enum(SHAPE_KINDS);
export type ShapeKind = z.infer<typeof ShapeKindSchema>;

export const ShapeLayerSchema = z.object({
  ...LayerBase,
  type: z.literal('shape'),
  shape: ShapeKindSchema,
  width: z.number().positive(),
  height: z.number().positive(),
  cornerRadius: z.number().min(0),
  fill: z.string(),
  stroke: z.string(),
  strokeWidth: z.number().min(0),
  /** Star tips / polygon sides. */
  points: z.number().int().min(3).max(64).default(5),
  /** Star inner radius as a fraction of the outer radius. */
  innerRadius: z.number().min(0).max(1).default(0.45),
  fillMode: FillModeSchema.default('solid'),
  gradientTo: z.string().default('#ffffff'),
  gradientAngle: z.number().default(90),
  /** Trim paths (stroke only): visible part of the outline, as fractions of its length. */
  trimStart: z.number().min(0).max(1).default(0),
  trimEnd: z.number().min(0).max(1).default(1),
  trimOffset: z.number().default(0),
  lineCap: z.enum(['butt', 'round', 'square']).default('round'),
});

export const CursorPointSchema = z.object({
  id: z.string(),
  /** Position in project pixels. */
  x: z.number(),
  y: z.number(),
  /** Arrival time, seconds relative to the layer start. */
  time: z.number().min(0),
});
export const CursorClickSchema = z.object({ id: z.string(), time: z.number().min(0) });

export const CursorLayerSchema = z.object({
  ...LayerBase,
  type: z.literal('cursor'),
  points: z.array(CursorPointSchema),
  clicks: z.array(CursorClickSchema),
  /** 0 = straight segments, 1 = fully smoothed spline. */
  smoothing: z.number().min(0).max(1),
  size: z.number().positive(),
  color: z.string(),
  rippleColor: z.string(),
});

export const LayerSchema = z.discriminatedUnion('type', [
  TextLayerSchema,
  ImageLayerSchema,
  ShapeLayerSchema,
  CursorLayerSchema,
]);
export type Layer = z.infer<typeof LayerSchema>;
export type LayerInput = z.input<typeof LayerSchema>;
export type TextLayer = z.infer<typeof TextLayerSchema>;
export type ImageLayer = z.infer<typeof ImageLayerSchema>;
export type ShapeLayer = z.infer<typeof ShapeLayerSchema>;
export type CursorLayer = z.infer<typeof CursorLayerSchema>;
export type CursorPoint = z.infer<typeof CursorPointSchema>;
export type LayerType = Layer['type'];

export const TransitionSchema = z.object({
  type: z.enum(['none', 'fade', 'slide', 'push', 'wipe', 'zoom', 'blur']),
  /** Seconds, at the start of the scene. */
  duration: z.number().positive(),
  /** Direction of travel of the incoming scene (slide/push/wipe). */
  direction: z.enum(['left', 'right', 'up', 'down']),
  easing: EasingSchema,
});
export type Transition = z.infer<typeof TransitionSchema>;

export const defaultTransition = (): Transition => ({ type: 'none', duration: 0.6, direction: 'left', easing: { type: 'easeInOut' } });

export const SceneSchema = z.object({
  id: z.string(),
  name: z.string(),
  /** Seconds from project start. */
  start: z.number().min(0),
  duration: z.number().positive(),
  /** Array order = z-order (first is drawn first, i.e. at the back). */
  layers: z.array(LayerSchema),
  /** null = show the project background. */
  background: z.string().nullable().default(null),
  transition: TransitionSchema.default(defaultTransition),
});
export type Scene = z.infer<typeof SceneSchema>;
export type SceneInput = z.input<typeof SceneSchema>;

export const AssetSchema = z.object({
  id: z.string(),
  originalName: z.string(),
  /** Path inside the project folder, e.g. assets/1a2b3c4d-logo.png */
  relativePath: z.string(),
  type: z.enum(['image', 'svg', 'font', 'audio']),
  /** sha256 of the original bytes. */
  hash: z.string(),
  /** For fonts: the CSS family name registered for this file. */
  fontFamily: z.string().optional(),
  width: z.number().optional(),
  height: z.number().optional(),
  /** For audio: length in seconds. */
  duration: z.number().optional(),
});
export type Asset = z.infer<typeof AssetSchema>;

export const AudioClipSchema = z.object({
  id: z.string(),
  name: z.string(),
  assetId: z.string(),
  /** Seconds from project start. */
  start: z.number().min(0),
  /** Seconds skipped at the beginning of the source file. */
  trimStart: z.number().min(0),
  duration: z.number().positive(),
  /** Linear gain: 1 = original level. */
  volume: z.number().min(0).max(4),
  fadeIn: z.number().min(0),
  fadeOut: z.number().min(0),
  muted: z.boolean(),
});
export type AudioClip = z.infer<typeof AudioClipSchema>;

export const SettingsSchema = z.object({
  durationSec: z.number().positive().max(3600),
  aspect: z.enum(['16:9', '9:16', '1:1', '4:5', 'custom']),
  width: z.number().int().min(16).max(7680),
  height: z.number().int().min(16).max(7680),
  fps: z.number().int().min(1).max(120),
  background: z.string(),
});
export type Settings = z.infer<typeof SettingsSchema>;

export const ProjectV2Schema = z.object({
  schemaVersion: z.literal(SCHEMA_VERSION),
  settings: SettingsSchema,
  scenes: z.array(SceneSchema),
  assets: z.array(AssetSchema),
  audio: z.array(AudioClipSchema).default(() => []),
});

/** Bring older project files up to the current schemaVersion. New fields are filled in by zod defaults. */
export function migrateProject(data: unknown): unknown {
  if (!data || typeof data !== 'object') return data;
  const d = data as { schemaVersion?: unknown };
  if (d.schemaVersion === 1) return { ...d, schemaVersion: 2 };
  return data;
}

export const ProjectSchema = z.preprocess(migrateProject, ProjectV2Schema);
export type Project = z.infer<typeof ProjectV2Schema>;
export type ProjectInput = z.input<typeof ProjectV2Schema>;

export const ASPECTS: Record<Exclude<Settings['aspect'], 'custom'>, [number, number]> = {
  '16:9': [16, 9],
  '9:16': [9, 16],
  '1:1': [1, 1],
  '4:5': [4, 5],
};

export function emptyProject(): Project {
  return {
    schemaVersion: SCHEMA_VERSION,
    settings: {
      durationSec: 15,
      aspect: '16:9',
      width: 3840,
      height: 2160,
      fps: 30,
      background: '#000000',
    },
    scenes: [],
    assets: [],
    audio: [],
  };
}

const EFFECTS = ['blur', 'shadowColor', 'shadowBlur', 'shadowOffsetX', 'shadowOffsetY'];

/** Properties that can carry keyframes, per layer type. */
export const ANIMATABLE: Record<LayerType, string[]> = {
  text: ['x', 'y', 'scale', 'rotation', 'opacity', 'fontSize', 'letterSpacing', 'color', 'gradientTo', 'gradientAngle', 'stroke', 'strokeWidth', ...EFFECTS],
  image: ['x', 'y', 'scale', 'rotation', 'opacity', 'width', 'height', ...EFFECTS],
  shape: [
    'x', 'y', 'scale', 'rotation', 'opacity', 'width', 'height', 'cornerRadius', 'fill',
    'innerRadius', 'trimStart', 'trimEnd', 'trimOffset', 'stroke', 'strokeWidth', 'gradientTo', 'gradientAngle', ...EFFECTS,
  ],
  cursor: ['opacity', 'scale', ...EFFECTS],
};
