// Single source of truth for the project file format (project.json).
// Every load/save goes through ProjectSchema.parse so bad files fail loudly.
import { z } from 'zod';

export const SCHEMA_VERSION = 1;

export const EasingSchema = z.discriminatedUnion('type', [
  z.object({ type: z.literal('linear') }),
  z.object({ type: z.literal('easeIn') }),
  z.object({ type: z.literal('easeOut') }),
  z.object({ type: z.literal('easeInOut') }),
  z.object({
    type: z.literal('cubicBezier'),
    x1: z.number().min(0).max(1),
    y1: z.number(),
    x2: z.number().min(0).max(1),
    y2: z.number(),
  }),
  z.object({
    type: z.literal('spring'),
    stiffness: z.number().positive(),
    damping: z.number().nonnegative(),
    mass: z.number().positive(),
  }),
]);
export type Easing = z.infer<typeof EasingSchema>;

/** Animatable values are numbers or CSS hex colours (#rrggbb / #rrggbbaa). */
export const KeyValueSchema = z.union([z.number(), z.string()]);

export const KeyframeSchema = z.object({
  id: z.string(),
  /** Seconds, relative to the layer's start. */
  time: z.number(),
  value: KeyValueSchema,
  /** Easing used from this keyframe to the next one. */
  easing: EasingSchema,
  /** Set when generated by an animation preset, so re-applying can replace it. */
  source: z.string().optional(),
});
export type Keyframe = z.infer<typeof KeyframeSchema>;

const LayerBase = {
  id: z.string(),
  name: z.string(),
  visible: z.boolean(),
  locked: z.boolean(),
  /** Seconds relative to the scene start. */
  start: z.number().min(0),
  duration: z.number().positive(),
  /** Anchor in normalised layer-local coordinates (0..1). */
  anchorX: z.number(),
  anchorY: z.number(),
  x: z.number(),
  y: z.number(),
  scale: z.number(),
  rotation: z.number(),
  opacity: z.number().min(0).max(1),
  /** Property name -> keyframes (sorted by time). */
  keyframes: z.record(z.string(), z.array(KeyframeSchema)),
};

export const TextLayerSchema = z.object({
  ...LayerBase,
  type: z.literal('text'),
  content: z.string(),
  fontFamily: z.string(),
  fontSize: z.number().positive(),
  fontWeight: z.number().int().min(100).max(900),
  lineHeight: z.number().positive(),
  letterSpacing: z.number(),
  align: z.enum(['left', 'center', 'right']),
  color: z.string(),
});

export const ImageLayerSchema = z.object({
  ...LayerBase,
  type: z.literal('image'),
  assetId: z.string(),
  width: z.number().positive(),
  height: z.number().positive(),
});

export const ShapeLayerSchema = z.object({
  ...LayerBase,
  type: z.literal('shape'),
  shape: z.enum(['rect', 'ellipse']),
  width: z.number().positive(),
  height: z.number().positive(),
  cornerRadius: z.number().min(0),
  fill: z.string(),
  stroke: z.string(),
  strokeWidth: z.number().min(0),
});

export const CursorPointSchema = z.object({
  id: z.string(),
  /** Position in project pixels. */
  x: z.number(),
  y: z.number(),
  /** Arrival time, seconds relative to the layer start. */
  time: z.number().min(0),
});
export const CursorClickSchema = z.object({ id: z.string(), time: z.number().min(0) });

export const CursorLayerSchema = z.object({
  ...LayerBase,
  type: z.literal('cursor'),
  points: z.array(CursorPointSchema),
  clicks: z.array(CursorClickSchema),
  /** 0 = straight segments, 1 = fully smoothed spline. */
  smoothing: z.number().min(0).max(1),
  size: z.number().positive(),
  color: z.string(),
  rippleColor: z.string(),
});

export const LayerSchema = z.discriminatedUnion('type', [
  TextLayerSchema,
  ImageLayerSchema,
  ShapeLayerSchema,
  CursorLayerSchema,
]);
export type Layer = z.infer<typeof LayerSchema>;
export type TextLayer = z.infer<typeof TextLayerSchema>;
export type ImageLayer = z.infer<typeof ImageLayerSchema>;
export type ShapeLayer = z.infer<typeof ShapeLayerSchema>;
export type CursorLayer = z.infer<typeof CursorLayerSchema>;
export type CursorPoint = z.infer<typeof CursorPointSchema>;
export type LayerType = Layer['type'];

export const SceneSchema = z.object({
  id: z.string(),
  name: z.string(),
  /** Seconds from project start. */
  start: z.number().min(0),
  duration: z.number().positive(),
  /** Array order = z-order (first is drawn first, i.e. at the back). */
  layers: z.array(LayerSchema),
});
export type Scene = z.infer<typeof SceneSchema>;

export const AssetSchema = z.object({
  id: z.string(),
  originalName: z.string(),
  /** Path inside the project folder, e.g. assets/1a2b3c4d-logo.png */
  relativePath: z.string(),
  type: z.enum(['image', 'svg', 'font']),
  /** sha256 of the original bytes. */
  hash: z.string(),
  /** For fonts: the CSS family name registered for this file. */
  fontFamily: z.string().optional(),
  width: z.number().optional(),
  height: z.number().optional(),
});
export type Asset = z.infer<typeof AssetSchema>;

export const SettingsSchema = z.object({
  durationSec: z.number().positive().max(3600),
  aspect: z.enum(['16:9', '9:16', '1:1', '4:5', 'custom']),
  width: z.number().int().min(16).max(7680),
  height: z.number().int().min(16).max(7680),
  fps: z.number().int().min(1).max(120),
  background: z.string(),
});
export type Settings = z.infer<typeof SettingsSchema>;

export const ProjectSchema = z.object({
  schemaVersion: z.literal(SCHEMA_VERSION),
  settings: SettingsSchema,
  scenes: z.array(SceneSchema),
  assets: z.array(AssetSchema),
});
export type Project = z.infer<typeof ProjectSchema>;

export const ASPECTS: Record<Exclude<Settings['aspect'], 'custom'>, [number, number]> = {
  '16:9': [16, 9],
  '9:16': [9, 16],
  '1:1': [1, 1],
  '4:5': [4, 5],
};

export function emptyProject(): Project {
  return {
    schemaVersion: SCHEMA_VERSION,
    settings: {
      durationSec: 15,
      aspect: '16:9',
      width: 3840,
      height: 2160,
      fps: 30,
      background: '#000000',
    },
    scenes: [],
    assets: [],
  };
}

/** Properties that can carry keyframes, per layer type. */
export const ANIMATABLE: Record<LayerType, string[]> = {
  text: ['x', 'y', 'scale', 'rotation', 'opacity', 'fontSize', 'letterSpacing', 'color'],
  image: ['x', 'y', 'scale', 'rotation', 'opacity'],
  shape: ['x', 'y', 'scale', 'rotation', 'opacity', 'width', 'height', 'cornerRadius', 'fill'],
  cursor: ['opacity', 'scale'],
};
